---
title: "Data & Resources"
---

This page contains links to the data we're using in our workshop, and a sample of a few useful resources online and in print. This is by no means a comprehensive list, but hopefully a launching pad for useful website and books. All of these examples provide code in same shape or form.

## {.tabset .tabset-fade}

### Datasets

This is a list of the data sources used in this workshop. For live-coding, please refer to this [**link**](https://dl.dropboxusercontent.com/s/k5w37n772eu5knx/cabw_script.R?dl=0), which will update everytime we save a file. That means you can refresh the page to see whatever code we are typing, and download this file at anytime.

 - [Full Dataset as a zipped folder](https://github.com/SCCWRP/CABW2018_R_training/raw/master/data/datazip.zip). Inside you'll find these files:
    - [Longitude-Latitude Data: `latlon.csv`](https://raw.githubusercontent.com/SCCWRP/CABW2018_R_training/master/data/latlon.csv)
    - [CSCI Data: `cscidat.csv`](https://raw.githubusercontent.com/SCCWRP/CABW2018_R_training/master/data/cscidat.csv)
    - [ASCI Data: `ascidat.csv`](https://raw.githubusercontent.com/SCCWRP/CABW2018_R_training/master/data/ascidat.csv)

### Resources

#### *R Lessons & Tutorials*

* [Software Carpentry: **R for Reproducible Scientific Analysis**](http://data-lessons.github.io/gapminder-R/)
* [Data Carpentry: **R for Data Analysis and Visualization of Ecological Data**](http://www.datacarpentry.org/R-ecology-lesson/)
* [Data Carpentry: **Data Organization in Spreadsheets**](http://www.datacarpentry.org/spreadsheet-ecology-lesson/)
* [**RStudio Webinars**, many topics](https://www.rstudio.com/resources/webinars/)
* [R For Cats: **Basic introduction site, with cats!**](http://rforcats.net/)
* [Topical cheatsheets from **RStudio**, also viewed from the help menu](http://www.rstudio.com/resources/cheatsheets/)
* [Cheatsheet from CRAN of **base R functions**](http://cran.r-project.org/doc/contrib/Short-refcard.pdf) 

#### *R eBooks/Courses*

* [Jenny Bryan's **Stat545.com**](http://stat545.com/)
* [Garrett Grolemund and Hadley Wickham's **R For Data Science**](http://r4ds.had.co.nz/)
* [Chester Ismay and Albert Y. Kim's **Modern DiveR**](https://ismayc.github.io/moderndiver-book/)
* [Julia Silge and David Robinson **Text Mining with R**](http://tidytextmining.com/)
* [Hadley Wikham's **Advanced R**](http://adv-r.had.co.nz/)

#### *Git/Github* 

* [Jenny Bryan's **Happy Git and Github for the useR**](http://happygitwithr.com/)
* [Coding Club **Intro to Github**](https://ourcodingclub.github.io/2017/02/27/git.html)
